# Site settings
name: Vipula Dissanayake
title: Vipula Dissanayake | Machine Learning Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://vipulasd.github.io/
baseurl: ''
email: vipula803@gmail.com
cover: https://vipulasd.github.io/img/og.png
logo: https://vipulasd.github.io/img/emojis/technologist.png
resume: https://vipulasd.github.io/resume.pdf
social:
  - title: email
    url: mailto:vipula803@gmail.com
  - title: instagram
    url: https://www.instagram.com/vipula.sd/
  - title: linkedin
    url: https://www.linkedin.com/in/vipulad/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
